blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, \
    BlogManagementListView

app_name = 'blog'

urlpatterns = [
    path('create/', BlogCreateView.as_view(template_name='blog/blog_form.html'), name='create'),
    path('', cache_page(60)(BlogListView.as_view(template_name='blog/blog_list.html')), name='list'),
    path('blog_management/', BlogManagementListView.as_view(template_name='blog/blog_management.html'), name='content'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view(template_name='blog/blog_detail.html')), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(template_name='blog/blog_form.html'), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(template_name='blog/blog_confirm_delete.html'), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    # path('chat/', include('chat.urls', namespace='chat')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
]


handler403 = 'mailing.views.custom_permission_denied'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from mailing.views import PartnerCreateView, ClientsListCreateView, mailing_panel, MailingCreateView, mailings_manage, \
    PartnerListView, MailingListView, MailingDetailView, toggle_block_status, MailingPartnersListView, \
    MailingPartnersDetailView, MailingPartnersUpdateView, MailingPartnersDeleteView, PartnersDetailView, \
    toggle_block_partners

app_name = 'mailing'

urlpatterns = [
    path('partner_registration/', PartnerCreateView.as_view(template_name='mailing/partner_registration.html'),
         name='partner_registration'),
    path('client_list_create/', ClientsListCreateView.as_view(), name='client_list_create'),
    path('mailing_management/', mailing_panel, name='mailing_panel'),
    path('mailing_form/', MailingCreateView.as_view(), name='mailing_form'),
    path('manage_mailing/', mailings_manage, name='mailings_manage'),
    path('partners_list_manage/', PartnerListView.as_view(), name='partners_list_manage'),
    path('mailings_list_manage/', MailingListView.as_view(), name='mailings_list_manage'),
    path('mailing_detail_manage/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail_manage'),
    path('toggle_block_status/<int:mailing_id>/', toggle_block_status, name='toggle_block_status'),
    path('mailings_list_user/', MailingPartnersListView.as_view(), name='mailings_list_user'),
    path('mailing_detail_user/<int:pk>/', MailingPartnersDetailView.as_view(), name='mailing_detail_user'),
    path('mailing_update_user/<int:pk>/', MailingPartnersUpdateView.as_view(), name='mailing_update_user'),
    path('mailing_confirm_delete/<int:pk>/', MailingPartnersDeleteView.as_view(), name='mailing_confirm_delete'),
    path('partners_detail_manage/<int:pk>/', PartnersDetailView.as_view(), name='partners_detail_manage'),
    path('toggle_block_partners/<int:partner_id>/', toggle_block_partners, name='toggle_block_partners'),

]

mailing/models.py
from datetime import datetime, timedelta

from django.db import models

from config.settings import TIME_CHOICES
from users.models import User
from utils import NULLABLE


class Client(models.Model):
    """
    Модель для создания клиента от пользователя
    """
    client = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, verbose_name='имя')
    surname = models.CharField(max_length=50, verbose_name='фамилия')
    email = models.EmailField(unique=True, verbose_name='почта')

    def __str__(self):
        return f'{self.name} {self.surname}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'
        ordering = ('name',)


class Partner(models.Model):
    """
    Модель для создания партнера, который использует рассылку
    """
    partner = models.OneToOneField(User, on_delete=models.CASCADE)
    name_company = models.CharField(max_length=50, verbose_name='название компании')
    address = models.CharField(max_length=50, verbose_name='адрес компании')
    phone = models.CharField(max_length=35, verbose_name='телефон')
    email_company = models.EmailField(unique=True, verbose_name='почта компании')
    is_active = models.BooleanField(default=True, verbose_name='блокировка партнера')

    def __str__(self):
        return f'{self.name_company} {self.email_company}'

    class Meta:
        verbose_name = 'партнер'
        verbose_name_plural = 'партнер'
        ordering = ('name_company',)


class ClientsList(models.Model):
    """
    Модель для создания списка клиентов для каждого партнера
    """

    partner = models.ForeignKey(Partner, on_delete=models.CASCADE)
    clients = models.ManyToManyField(Client, verbose_name='клиент для списка')
    name = models.CharField(max_length=100, verbose_name='название списка')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'список клиентов для рассылки'
        verbose_name_plural = 'список клиентов для рассылки'
        ordering = ('name',)


class Mailing(models.Model):
    """
    Модель для настройки рассылки
    """
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE)
    clients_list = models.ManyToManyField(ClientsList, verbose_name='список клиентов для рассылки')
    date = models.DateTimeField(auto_now=True, editable=False, verbose_name='дата создания')
    periodicity = models.CharField(max_length=50, verbose_name='периодичность', choices=TIME_CHOICES)
    status = models.CharField(max_length=50, default='создана', verbose_name='статус')
    name_mailing = models.CharField(max_length=50, verbose_name='название рассылки', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='блокировка рассылки')

    def __str__(self):
        return f'{self.name_mailing}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылка'
        ordering = ('name_mailing',)
        permissions = [
            (
                'can_blocked',
                'can_blocked'
            )
        ]


class Message(models.Model):
    """
    Модель для сообщения
    """
    mailing = models.OneToOneField(Mailing, on_delete=models.CASCADE)
    theme = models.CharField(max_length=100, verbose_name='тема сообщения для рассылки')
    text = models.TextField(verbose_name='текст сообщения для рассылки')


class LogMailing(models.Model):
    """
    Модель для логов рассылки
    """
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)
    last_date = models.DateTimeField(auto_now=True, editable=False, verbose_name='дата последней попытки')
    status = models.CharField(max_length=20, verbose_name='статус попытки')
    server_response = models.CharField(max_length=200, verbose_name='ответ почтового сервера', **NULLABLE)

mailing/forms.py
from django import forms
from mailing.models import Partner, Client, ClientsList, Mailing, Message


class PartnerForm(forms.ModelForm):
    """
    Форма для валидации и стилизации партнера
    """

    class Meta:
        model = Partner
        fields = ['name_company', 'address', 'phone', 'email_company']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(forms.ModelForm):
    """
    Форма для валидации и стилизации клиента
    """

    class Meta:
        model = Client
        fields = ['name', 'surname', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientsListForm(forms.ModelForm):
    """
    Форма для списка клиентов для партнера
    """

    class Meta:
        model = ClientsList
        fields = ['name', 'clients']

    # форма для добавления клиента в список
    clients = forms.ModelMultipleChoiceField(
        queryset=Client.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )


class MailingForm(forms.ModelForm):
    """
    Форма для рассылки
    """

    class Meta:
        model = Mailing
        fields = ['name_mailing', 'clients_list', 'periodicity']

    # форма для добавления списка клиентов
    clients_list = forms.ModelMultipleChoiceField(
        queryset=ClientsList.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )


class MessageForm(forms.ModelForm):
    """
    Форма для сообщения
    """

    class Meta:
        model = Message
        fields = ['theme', 'text']

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from mailing.forms import PartnerForm, ClientsListForm, MailingForm, MessageForm
from mailing.models import Partner, ClientsList, Mailing, LogMailing


class PartnerCreateView(LoginRequiredMixin, CreateView):
    """
    Класс для создания блоговой записи
    """
    model = Partner
    form_class = PartnerForm
    template_name = 'mailing/partner_registration.html'
    success_url = reverse_lazy('main:index')

    def form_valid(self, form):
        # Устанавливаем пользователя и partner_id перед сохранением Partner
        form.instance.user = self.request.user
        form.instance.partner_id = self.request.user.id
        return super().form_valid(form)


class ClientsListCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер для создания списка клиентов
    """
    model = ClientsList
    form_class = ClientsListForm
    template_name = 'mailing/client_list_create.html'
    success_url = reverse_lazy('mailing:mailing_panel')

    def form_valid(self, form):
        partner = self.request.user.partner
        form.instance.partner = partner
        response = super().form_valid(form)
        return response


class MailingCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер для создания рассылки и сообщения
    """
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy('mailing:mailing_panel')

    def form_valid(self, form):
        partner = self.request.user.partner
        form.instance.partner = partner
        response = super().form_valid(form)

        message_form = MessageForm(self.request.POST)
        if message_form.is_valid():
            message = message_form.save(commit=False)
            message.mailing = self.object
            message.save()

        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message_form'] = MessageForm()
        return context


def mailing_panel(request):
    """
   Вывод страницы с управлением рассылкой
    """
    return render(request, 'mailing/mailing_management.html')


def mailings_manage(request):
    """
   Вывод страницы с управлением рассылкой
    """
    return render(request, 'mailing/manage_mailing.html')


class PartnerListView(LoginRequiredMixin, ListView):
    """
    Контроллер для создания списка пользователей сервиса
    """
    model = Partner
    form_class = PartnerForm
    template_name = 'mailing/partners_list_manage.html'


class MailingListView(LoginRequiredMixin, ListView):
    """
    Контроллер для создания списка рассылок для менеджера
    """
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailings_list_manage.html'


class MailingDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер для просмотра рассылки для менеджера
    """
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_detail_manage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = self.object.message
        return context


@login_required
def toggle_block_status(request, mailing_id):
    """
   Функция для переключения статуса активности рассылки
    """
    mailing = get_object_or_404(Mailing, id=mailing_id)

    # Переключаем статус блокировки
    if request.user.has_perm('mailing.can_blocked'):
        mailing.is_active = not mailing.is_active
        mailing.save()
        return redirect('mailing:mailings_list_manage')
    else:
        # Обработка случая, когда у пользователя нет нужных прав
        return render(request, 'main/403.html')


@login_required
def toggle_block_partners(request, partner_id):
    """
   Функция для переключения статуса активности у партнера
    """
    partners = get_object_or_404(Partner, id=partner_id)

    # Переключаем статус блокировки
    if request.user.has_perm('mailing.can_blocked'):
        partners.is_active = not partners.is_active
        partners.save()
        return redirect('mailing:partners_list_manage')
    else:
        # Обработка случая, когда у пользователя нет нужных прав
        return render(request, 'main/403.html')


def custom_permission_denied(request, exception):
    """
    При ошибке перевод на собственную страницу
    """
    return render(request, 'main/403.html', status=403)


class MailingPartnersListView(LoginRequiredMixin, ListView):
    """
     Класс для создания списка рассылок для менеджера
     """
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailings_list_user.html'

    def get_queryset(self):
        # Фильтрация рассылок по текущему пользователю
        return Mailing.objects.filter(partner__partner=self.request.user)


class MailingPartnersDetailView(LoginRequiredMixin, DetailView):
    """
    Класс для просмотра рассылки для менеджера
    """
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_detail_user.html'

    def get_queryset(self):
        # Фильтрация рассылок по текущему пользователю
        return Mailing.objects.filter(partner__partner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = self.object.message

        # Получение статистики из логов рассылки
        logs_fail = LogMailing.objects.filter(mailing=self.object).filter(status='неудачно')
        logs_good = LogMailing.objects.filter(mailing=self.object).filter(status='успешно').count
        context['logs_fail'] = logs_fail
        context['logs_good'] = logs_good
        return context


class MailingPartnersUpdateView(LoginRequiredMixin, UpdateView):
    """
    Класс для просмотра рассылки для менеджера
    """
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_update_user.html'
    success_url = reverse_lazy('mailing:mailings_list_user')


class MailingPartnersDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер для показа рассылок партнеру
    """

    model = Mailing
    success_url = reverse_lazy('mailing:mailings_list_user')
    template_name = 'mailing/mailing_confirm_delete.html'


class PartnersDetailView(LoginRequiredMixin, DetailView):
    """
    Класс для просмотра рассылки для менеджера
    """
    model = Partner
    form_class = PartnerForm
    template_name = 'mailing/partners_detail_manage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

mailing/templates/mailing/client_list_create.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12">
  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Сохранить">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>




{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12">
  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <p> Хотите удалить рассылку "{{ object.name_mailing }}"?</p>
            <button type="submit" class="btn btn-danger">Подтвердить</button>
            <a href="{% url 'mailing:mailings_list_user' %}" class="btn btn-warning">Отмена</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_detail_manage.html
<!-- mailing_detail_manage.html -->
{% extends 'main/base.html' %}
{% load mediapath %}

{% block content %}

<div class="container">
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <h3 class="card-title">{{ object.title }}</h3>
                <small class="text-body-secondary">Дата публикации: {{ object.date|date:'d-m-Y H:i:s' }}</small><br><br>

                <!-- Вывод информации о рассылке -->
                <h4>Сообщение рассылки:</h4>
                <p>{{ object.message.theme }}: {{ object.message.text }}</p>

                <!-- Вывод информации о партнере -->
                <h4>Информация о партнере:</h4>
                <p>Название компании: {{ object.partner.name_company }}</p>
                <p>Адрес компании: {{ object.partner.address }}</p>
                <p>Телефон: {{ object.partner.phone }}</p>
                <p>Почта компании: {{ object.partner.email_company }}</p>

                <!-- Форма для блокировки/разблокировки -->
                <form method="post" action="{% url 'mailing:toggle_block_status' object.id %}">
                    {% csrf_token %}
                    <button type="submit">
                        {% if object.is_active %}
                            Заблокировать
                        {% else %}
                            Разблокировать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_detail_user.html
<!-- mailing_detail_user.html -->
{% extends 'main/base.html' %}
{% load mediapath %}

{% block content %}

<div class="row row-cols-1 row-cols-md-2 g-4">
    <div class="col-md-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <h3 class="card-title">{{ object.name_mailing }}</h3>
                <small class="text-body-secondary">Дата создания: {{ object.date|date:'d-m-Y H:i:s' }}</small><br><br>

                <!-- Вывод информации о рассылке -->
                <h4>Сообщение рассылки:</h4>
                <p>{{ object.message.theme }}: {{ object.message.text }}</p>

                <!-- Вывод статистики из логов рассылки -->
                <h4>Статистика рассылки:</h4>

                <p>Количество успешных отправлений: {{ logs_good }}</p>
                {% if logs_fail %}
                    <ul>
                        <li>{{ logs_fail.status }} - {{ logs_fail.last_date }} - {{ logs_fail.server_response }}</li>
                        <!-- Добавьте другие поля, которые вы хотите отобразить из логов -->

                    </ul>
                {% else %}
                    <p>Нет статистики для этой рассылки.</p>
                {% endif %}

                <div class="btn-group">
                  <a href="{% url 'mailing:mailing_update_user' object.pk %}"
                     class="btn btn-sm btn-outline-secondary">Edit</a>
                  <a href="{% url 'mailing:mailing_confirm_delete' object.pk %}"
                     class="btn btn-sm btn-outline-secondary">Delete</a>
              </div>

            </div>
        </div>
    </div>
    <div class="col-md-4">
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12">
  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              {{ message_form.as_p }}
              <input type="submit" value="Сохранить">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>




{% endblock %}

mailing/templates/mailing/mailing_management.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12">
  <form class="row" method="post" enctype="multipart/form-data">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">
            Управление рассылками
            {% if user.partner %}
              {% if user.partner.is_active == True %}
                <li><a href="{% url 'mailing:client_list_create' %}" class="text">Создать свой список клиентов</a></li>
                <li><a href="{% url 'mailing:mailing_form' %}" class="text">Создать рассылку</a></li>
                <li><a href="{% url 'mailing:mailings_list_user' %}" class="text">Просмотреть свои рассылки</a></li>
              {% endif %}
            {% else %}
              <li><a href="{% url 'mailing:partner_registration' %}" class="text">Зарегистрироваться как партнер</a></li>
              <li><a href="{% url 'mailing:client_list_create' %}" class="text">Создать свой список клиентов</a></li>
              <li><a href="{% url 'mailing:mailing_form' %}" class="text">Создать рассылку</a></li>
              <li><a href="{% url 'mailing:mailings_list_user' %}" class="text">Просмотреть свои рассылки</a></li>
            {% endif %}
          </h3>
      </div>
    </div>
  </form>
</div>


{% endblock %}

mailing/templates/mailing/mailing_update_user.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12">
  <div class="row">
    <div class="col-7">
      <div class="card">
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn btn-success">
              {% if object %}
                Сохранить
              {% else %}
                Создать
              {% endif %}
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

mailing/templates/mailing/mailings_list_manage.html
{% extends 'main/base.html' %}
{% load mediapath %}

{% block content %}

<div class="col-12 mb-5">
</div>
<div class="container">
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for object in object_list %}
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <div class="card-body">
                <p class="card-text">
                  Наименование рассылки: {{ object.name_mailing }}
                </p>
                <p class="card-text">
                  Статус отправки: {{ object.status }}
                </p>
                {% if object.is_active is True %}
                  <p class="card-text">
                      Статус блокировки: рассылка не заблокирована
                  </p>
                {% else %}
                  <p class="card-text">
                      Статус блокировки: рассылка заблокирована
                  </p>
                {% endif %}
                 <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'mailing:mailing_detail_manage' object.pk %}"
                          class="btn btn-sm btn-outline-secondary">Подробнее</a>
                      </div>
                  </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

mailing/templates/mailing/mailings_list_user.html
{% extends 'main/base.html' %}
{% load mediapath %}

{% block content %}

<div class="col-12 mb-5">
</div>
<div class="container">
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for object in object_list %}
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <div class="card-body">
                <p class="card-text">
                  {{ object.name_mailing }}
                </p>
                <p class="card-text">
                  {{ object.status }}
                  {% if object.is_active == True %}
                    <p>Рассылка активна</p>
                  {% else %}
                    <p>Рассылка заблокирована</p>
                  {% endif %}
                </p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'mailing:mailing_detail_user' object.pk %}"
                          class="btn btn-sm btn-outline-secondary">Подробнее</a>
                      </div>
                  </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

mailing/templates/mailing/manage_mailing.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12">
  <form class="row" method="post" enctype="multipart/form-data">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">
            Управление пользователями и рассылками
            <li><a href="{% url 'mailing:partners_list_manage' %}" class="text">Просмотреть пользователей сервиса</a></li>
            <li><a href="{% url 'mailing:mailings_list_manage' %}" class="text">Просмотреть рассылки</a></li>
          </h3>

      </div>
    </div>
  </form>
</div>


{% endblock %}

mailing/templates/mailing/partner_registration.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12">
  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Зарегистрировать компанию</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>




{% endblock %}

mailing/templates/mailing/partners_detail_manage.html
<!-- partner_detail_manage.html -->
{% extends 'main/base.html' %}
{% load mediapath %}

{% block content %}

<div class="container">
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <h3 class="card-title">{{ object.name_company }}</h3>

                <!-- Вывод информации о рассылке -->
                <p>Адрес: {{ object.address }}</p>
                <p>Телефон: {{ object.phone }}</p>
                <p>Почта компании: {{ object.email_company }}</p>

                <!-- Форма для блокировки/разблокировки -->
                <form method="post" action="{% url 'mailing:toggle_block_partners' partner_id=object.id %}">
                    {% csrf_token %}
                    <button type="submit">
                        {% if object.is_active %}
                            Заблокировать
                        {% else %}
                            Разблокировать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
</div>

{% endblock %}

mailing/templates/mailing/partners_list_manage.html
{% extends 'main/base.html' %}
{% load mediapath %}

{% block content %}

<div class="col-12 mb-5">
</div>
<div class="container">
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for object in object_list %}
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <div class="card-body">
                <p class="card-text">
                  Наименование компании: {{ object.name_company }}
                </p>
                {% if object.is_active is True %}
                  <p class="card-text">
                      Статус блокировки: компания не заблокирована
                  </p>
                {% else %}
                  <p class="card-text">
                      Статус блокировки: компания заблокирована
                  </p>
                {% endif %}
                 <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'mailing:partners_detail_manage' object.pk %}"
                          class="btn btn-sm btn-outline-secondary">Подробнее</a>
                      </div>
                  </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>



{% endblock %}