blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, \
    BlogManagementListView

app_name = 'blog'

urlpatterns = [
    path('create/', BlogCreateView.as_view(template_name='blog/blog_form.html'), name='create'),
    path('', cache_page(60)(BlogListView.as_view(template_name='blog/blog_list.html')), name='list'),
    path('blog_management/', BlogManagementListView.as_view(template_name='blog/blog_management.html'), name='content'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view(template_name='blog/blog_detail.html')), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(template_name='blog/blog_form.html'), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(template_name='blog/blog_confirm_delete.html'), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    # path('chat/', include('chat.urls', namespace='chat')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
]


handler403 = 'mailing.views.custom_permission_denied'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    """
    Модель для создания блоговой записи
    """
    title = models.CharField(max_length=150, verbose_name='заголовок')
    content = models.TextField(verbose_name='Контент')
    image = models.ImageField(upload_to='material/', verbose_name='изображение')
    create_date = models.DateTimeField(auto_now_add=True)
    count = models.IntegerField(default=0, verbose_name='кол-во просмотров')
    date = models.DateTimeField(auto_now=True, editable=False, verbose_name='дата создания')

    def __str__(self):
        return f'{self.title}. {self.content}.'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блог'
        ordering = ('title',)

blog/forms.py
from django import forms
from blog.models import Blog


class BlogForm(forms.ModelForm):
    """
    Форма для валидации и стилизации блоговой записи
    """

    class Meta:
        model = Blog
        fields = ['id', 'title', 'content', 'image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


from blog.forms import BlogForm
from blog.models import Blog


class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """
    Класс для создания блоговой записи
    """
    model = Blog
    form_class = BlogForm
    template_name = 'blog/blog_form.html'
    success_url = reverse_lazy('blog:content')
    permission_required = 'blog.add_blog'


class BlogListView(LoginRequiredMixin, ListView):
    """
    Класс для создания списка блоговых записей
    """
    model = Blog
    form_class = BlogForm
    template_name = 'blog/blog_list.html'


class BlogManagementListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """
    Класс для просмотра списка блоговых записей только контент-менеджером
    """
    model = Blog
    form_class = BlogForm
    template_name = 'blog/blog_management.html'
    permission_required = 'blog.add_blog'


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count += 1
        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """
    Класс позволяет редактировать запись
    """
    model = Blog
    form_class = BlogForm
    template_name = 'blog/blog_form.html'
    permission_required = 'blog.change_blog'

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')
    template_name = 'blog/blog_confirm_delete.html'
    permission_required = 'blog.delete_blog'

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12">
  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <p> Хотите удалить публикацию "{{ object.title }}"?</p>
            <button type="submit" class="btn btn-danger">Подтвердить</button>
            <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}
{% load mediapath %}

{% block content %}

<div class="row row-cols-1 row-cols-md-2 g-4">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <h3 class="card-title">{{ object.title }}</h3>
                <small class="text-body-secondary">Дата публикации: {{ object.date|date:'d-m-Y H:i:s' }}</small><br><br>
                <img class="card-img-top"
                    src="{% mediapath object.image %}"
                    alt="Card image cap">
                <strong>Содержание:</strong>
                <ul>
                    <li>{{ object.content }}</li>
                </ul>
                <strong>Количество просмотров: {{ object.count }}</strong>
            </div>
        </div>
    </div>
    <div class="col-md-4">
    </div>
</div>


{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12">
  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Сохранить</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>




{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}
{% load mediapath %}

{% block content %}

<div class="col-12 mb-5">
</div>
<div class="container">
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      {% for object in object_list %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow"> <!--bg-primary-->
          <img class="card-img-top"
               src="{% mediapath object.image %}"
               width="16" height="300">
      <div class="card body">
          <p class="card-text">
                {{ object|title|truncatechars:100 }}
          </p>
          <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                  <a href="{% url 'blog:view' object.pk %}"
                     class="btn btn-sm btn-outline-secondary">View</a>
              </div>
          </div>
      </div>
    </div>
  </div>
{% endfor %}


{% endblock %}

blog/templates/blog/blog_management.html
{% extends 'main/base.html' %}
{% load mediapath %}

{% block content %}

<div class="col-12 mb-5">
    <button type="submit" class="btn btn-success">
        <a href="{% url 'blog:create' %}" class="text-white">Добавить материал</a>
    </button>
</div>
<div class="container">
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      {% for object in object_list %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow"> <!--bg-primary-->
          <img class="card-img-top"
               src="{% mediapath object.image %}"
               width="16" height="300">
      <div class="card body">
          <p class="card-text">
                {{ object|title }}
          </p>
          <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                  <a href="{% url 'blog:view' object.pk %}"
                     class="btn btn-sm btn-outline-secondary">View</a>
                  <a href="{% url 'blog:edit' object.pk %}"
                     class="btn btn-sm btn-outline-secondary">Edit</a>
                  <a href="{% url 'blog:delete' object.pk %}"
                     class="btn btn-sm btn-outline-secondary">Delete</a>
              </div>
          </div>
      </div>
    </div>
  </div>
{% endfor %}


{% endblock %}