blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, \
    BlogManagementListView

app_name = 'blog'

urlpatterns = [
    path('create/', BlogCreateView.as_view(template_name='blog/blog_form.html'), name='create'),
    path('', cache_page(60)(BlogListView.as_view(template_name='blog/blog_list.html')), name='list'),
    path('blog_management/', BlogManagementListView.as_view(template_name='blog/blog_management.html'), name='content'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view(template_name='blog/blog_detail.html')), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(template_name='blog/blog_form.html'), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(template_name='blog/blog_confirm_delete.html'), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    # path('chat/', include('chat.urls', namespace='chat')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
]


handler403 = 'mailing.views.custom_permission_denied'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from mailing.views import PartnerCreateView, ClientsListCreateView, mailing_panel, MailingCreateView, mailings_manage, \
    PartnerListView, MailingListView, MailingDetailView, toggle_block_status, MailingPartnersListView, \
    MailingPartnersDetailView, MailingPartnersUpdateView, MailingPartnersDeleteView, PartnersDetailView, \
    toggle_block_partners

app_name = 'mailing'

urlpatterns = [
    path('partner_registration/', PartnerCreateView.as_view(template_name='mailing/partner_registration.html'),
         name='partner_registration'),
    path('client_list_create/', ClientsListCreateView.as_view(), name='client_list_create'),
    path('mailing_management/', mailing_panel, name='mailing_panel'),
    path('mailing_form/', MailingCreateView.as_view(), name='mailing_form'),
    path('manage_mailing/', mailings_manage, name='mailings_manage'),
    path('partners_list_manage/', PartnerListView.as_view(), name='partners_list_manage'),
    path('mailings_list_manage/', MailingListView.as_view(), name='mailings_list_manage'),
    path('mailing_detail_manage/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail_manage'),
    path('toggle_block_status/<int:mailing_id>/', toggle_block_status, name='toggle_block_status'),
    path('mailings_list_user/', MailingPartnersListView.as_view(), name='mailings_list_user'),
    path('mailing_detail_user/<int:pk>/', MailingPartnersDetailView.as_view(), name='mailing_detail_user'),
    path('mailing_update_user/<int:pk>/', MailingPartnersUpdateView.as_view(), name='mailing_update_user'),
    path('mailing_confirm_delete/<int:pk>/', MailingPartnersDeleteView.as_view(), name='mailing_confirm_delete'),
    path('partners_detail_manage/<int:pk>/', PartnersDetailView.as_view(), name='partners_detail_manage'),
    path('toggle_block_partners/<int:partner_id>/', toggle_block_partners, name='toggle_block_partners'),

]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import UserProfileListView, UserProfileDetailView, administrative_panel, like_view, BlogListView


app_name = MainConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='main'),
    path('skylove_list_view/', UserProfileListView.as_view(), name='skylove_list_view'),
    path('main/like/', like_view, name='like_view'),
    path('administrative_panel/', administrative_panel, name='administrative_panel'),
    path('profile_view/<int:pk>', UserProfileDetailView.as_view(), name='profile_view'),

]

users/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, activate, email_activate, restore_password, VerifyEmailView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('activate/<str:uid>/', activate, name="activate"),
    path('email_activated/', email_activate, name="email_activated"),
    path('restore_password/', restore_password, name="restore_password"),
    path('verify_email/<int:pk>/', VerifyEmailView.as_view(), name='verify_email'),
]

main/models.py
from django.db import models

from users.models import User


class Likes(models.Model):
    """
    Модель для записи лайка (кто лайкнул, кого лайкнул)
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes_given')
    liked_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes_received')
    created_at = models.DateTimeField(auto_now_add=True)

main/views.py
from django.views.decorators.cache import cache_page

from blog.forms import BlogForm
from blog.models import Blog
from mailing.models import Mailing, Client
from users.models import User

from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import permission_required


from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from main.utils import record_like


class UserProfileListView(LoginRequiredMixin, ListView):
    """
    Класс для создания списка анкет
    """
    model = User
    template_name = 'main/skylove_list_view.html'
    # permission_required = 'user.view_user'


class UserProfileDetailView(LoginRequiredMixin, DetailView):
    """
    Класс для отображения анкеты
    """

    model = User
    template_name = 'main/profile_view.html'
    # permission_required = 'user.view_user'

#применяем кэширование контроллера
@cache_page(60)
@csrf_exempt
@require_POST
def like_view(request):
    try:
        # Получаем id текущего пользователя
        user_id = request.user.id

        # Получаем id пользователя, которого лайкнули
        liked_user_id = request.POST.get('liked_user_id')
        print('current_user_id:', user_id)
        print('liked_user_id:', liked_user_id)

        # Вызываем функцию для записи лайка
        record_like(user_id, int(liked_user_id))

        return JsonResponse({'status': 'success'})
    except Exception as e:
        print('Error:', e)
        return JsonResponse({'status': 'error', 'message': str(e)})


@permission_required('mailing.can_blocked')
def administrative_panel(request):
    return render(request, 'main/administrative_panel.html')


class BlogListView(ListView):
    """
    Класс для создания списка блоговых записей
    """
    model = Blog
    form_class = BlogForm
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Получите общее количество рассылок
        total_mailings = Mailing.objects.count()

        active_mailings = Mailing.objects.filter(is_active=True).count()

        total_clients = Client.objects.count()

        # Передайте информацию в контекст
        context['total_mailings'] = total_mailings
        context['active_mailings'] = active_mailings
        context['total_clients'] = total_clients

        return context

main/templates/main/administrative_panel.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12">
  <form class="row" method="post" enctype="multipart/form-data">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">
            Управление сайтом
            {% if perms.mailing.can_blocked %}
            <li><a href="{% url 'blog:content' %}" class="text">Контент</a></li>
            <li><a href="{% url 'mailing:mailings_manage' %}" class="text">Рассылки</a></li>
            {% endif %}
          </h3>

      </div>
    </div>
  </form>
</div>


{% endblock %}

main/templates/main/base.html
{% load static %}

<!doctype html>

<html lang="en">
  <head>
  <style>
    body {
          background-image: url('https://catherineasquithgallery.com/uploads/posts/2021-03/1614603752_17-p-belii-fon-s-serdtsem-17.jpg');
    <!--      background-repeat: no-repeat;-->
          background-attachment: fixed;
          background-size: 20% 30%;
        }
    </style>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

<!--    <title>Магазин "Копеечка"</title>-->

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>

  <div class="pricing-header px-3 py-3 pt-md-5 pt-md-4 mx-auto text-center">
    <h2 class="display-4">Skylove</h2>
    <p class="lead">найди свою любовь</p>
  </div>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            {% include 'main/includes/inc_main_menu.html' %}
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
<!--          Кнопка с выплывающим меню-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
<!--          Картинка выплывающего меню-->

          </a>
        </div>
      </div>
    </header>

    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row">
          {% block content%}
          {% endblock %}
        </div>
      </div>
    </div>


    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
        <p>&copy; 2023 - {% now 'Y' %}</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
  </body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load mediapath %}

{% block content %}


<div class="container">
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="col-13">
        <div class="card">
          <div class="row">
            {% for object in object_list %}
            {% if forloop.counter > object_list|length|add:"-3" %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top"
                     src="{% mediapath object.image %}"
                     width="16" height="300">
                <div class="card-body">
                  <p class="card-text">
                    {{ object|title|truncatechars:50 }}
                  </p>

                <div class="btn-group d-flex justify-content-center">
                  <a href="{% url 'blog:view' object.pk %}"
                     class="btn btn-sm btn-outline-secondary text-center">Подробнее</a>
                </div>

                </div>
              </div>
            </div>
            {% endif %}
            {% endfor %}
          </div>
          {% if user.is_authenticated %}
              <a href="/blog/" class="btn btn-sm btn-outline-secondary text-center">Для подробной информации кликни сюда</a>
          {% else %}
              <a href="{% url 'users:login' %}" class="btn btn-sm btn-outline-secondary text-center">Авторизуйтесь, чтобы получить больше возможностей сайта</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% if user.is_authenticated %}
    <div class="col-md-5">
        <div class="card mb-4 rounded-3 box-shadow">
            <ul class="list-group">

                <li class="list-group-item text-center">
                    <h5>SkyLove</h5>
                </li>
                <li class="list-group-item text-center">
                    <h5>Ваша анкета:</h5>
                    <img src="{{ request.user.avatar.url }}" alt="Avatar" width="100" height="100">
                    <p>{{ user.name }} {{ user.surname }}</p>
                    <p>{{ user.age }} лет</p>
                    <p>Пол: {{ user.sex }}</p>
                    <p>{{ user.country }}. {{ user.city }}</p>
                    <p>{{ user.description }}</p>
                </li>
                <li class="list-group-item text-center">
                    <a href="{% url 'main:skylove_list_view' %}" class="btn text-center">Начать знакомиться</a>
                </li>
            </ul>
        </div>
    </div>

    <div class="col-md-5 offset-md-2">
        <div class="card mb-4 rounded-3 box-shadow">
            <div class="card-header py-3">
                <h5>Рекламный сервис:</h5>
                <p>Количество рассылок на данный момент: {{ total_mailings }}</p>
                <p>Наших уникальных клиентов для рассылки: {{ total_clients }}</p>
                <p>Количество активных рассылок: {{ active_mailings }}</p>
            </div>
            <div class="card-body">
            <li class="list-group-item text-center">
                <a href="{% url 'mailing:partner_registration' %}" class="btn text-center">Стать нашим партнером</a>
            </li>
            </div>
        </div>
    </div>
{% endif %}

{% endblock %}

main/templates/main/new_questionnaire.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12">
  <div class="row">
    <div class="col-7">
      <div class="card">
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn btn-success">
              {% if object %}
                Сохранить
              {% else %}
                Создать
              {% endif %}
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

main/templates/main/profile_view.html
{% extends 'main/base.html' %}
{% load mediapath %}

{% block content %}

<div class="row row-cols-1 row-cols-md-2 g-4">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <h3 class="card-title">Пользователь:</h3>
                <ul>
                    <li>{{ questionnaire.name }} {{ questionnaire.surname }}, {{ questionnaire.age }} лет</li>
                </ul>
                <img class="card-img-top"
                    src="{% mediapath questionnaire.avatar %}"
                    alt="Card image cap">
                <strong>Информация:</strong>
                <ul>
                    <li>{{ questionnaire.city }}</li>
                </ul>
                <strong>БИО:</strong>
                <ul>
                    <li>{{ questionnaire.description }}</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4">
    </div>
</div>

{% endblock %}

main/templates/main/questionnaire_delete.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12">
  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <p> Хотите удалить анкету "{{ object.name }} {{ object.surname }}"?</p>
            <button type="submit" class="btn btn-danger">Подтвердить</button>
            <button type="button" onclick="window.location.href = '{% url 'main:questionnaire_update' object.pk %}';" class="btn btn-sm btn-outline-info">Отмена</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

main/templates/main/questionnaire_update.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12">
  <div class="row">
    <div class="col-7">
      <div class="card">
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn btn-success">
              {% if object %}
                Сохранить
              {% else %}
                Создать
              {% endif %}
            </button>
            <a href="{% url 'main:questionnaire_delete' object.pk %}" class="btn btn-warning">Удалить анкету</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

main/templates/main/skylove_list_view.html
{% extends 'main/base.html' %}
{% load mediapath %}

{% block content %}

<style>
    .card-container {
        position: relative;
    }

    .scattering {
        width: 80px;
        height: 80px;
        position: absolute;
        cursor: pointer;
        font-size: 120px;
    }

    .scattering.like {
        color: red;
        left: 115%; /* Отцентрированная кнопка Like */
        top: 1%; /* Отступ сверху для кнопки Like */
        transform: translateX(-50%);
    }

    .scattering.dislike {
        color: black; /* Цвет кнопки дизлайка */
        left: -30%; /* Отцентрированная кнопка Dislike */
        top: 1%; /* Отступ сверху для кнопки Dislike */
        transform: translateX(-50%);
        border: none; /* Убираем границу */
        background-color: transparent; /* Прозрачный фон */
    }

    .card {
        display: none;
    }
</style>

<body>
    <div class="container">
        <header>
            <div class="pricing-header p-3 pb-md-4 mx-auto text-left">
                <img src="{{ request.user.avatar.url }}" alt="Avatar" width="40" height="40">
                <h4 class="display-4 fw-normal text-body-emphasis text-center">Найдите себе пару, {{request.user.name}} </h4>
            </div>
        </header>
    </div>
    <div class="col-md-3 text-center"></div>
    <div class="col-md-6 text-center">
        {% for liked_user in object_list %}
            {% if liked_user != request.user %}
                <div class="card mx-auto" data-liked-user-id="{{ liked_user.id }}">
                    {% if liked_user.avatar %}
                        <img class="card-img-top"
                            src="{{ liked_user.avatar.url }}"
                            width="16" height="300"
                            alt="Card image cap">
                    {% else %}
                        <p>Пользователь не загрузил изображение.</p>
                    {% endif %}

                    <h2>{{ liked_user.name }} {{ liked_user.surname }}</h2>
                    <p>{{ liked_user.age }} лет. </p>
                    <button type="button" class="btn btn-sm btn-outline-info">Подробнее</button>
                <div class="scattering like" onclick="sendAction('like', '{{ liked_user.id }}')" data-liked-user-id="{{ liked_user.id }}">&#x1F497;</div>
                <div class="scattering dislike" onclick="showCard(1)" data-liked-user-id="{{ liked_user.id }}">👎</div>
                </div>
            {% endif %}
        {% endfor %}
    </div>



<script>
    let currentCard = 0;

    function showCard(n) {
        const cards = document.getElementsByClassName('card');
        currentCard += n;

        if (currentCard >= cards.length) {
            currentCard = 0;
        }

        if (currentCard < 0) {
            currentCard = cards.length - 1;
        }

        for (let i = 0; i < cards.length; i++) {
            cards[i].style.display = 'none';
        }

        cards[currentCard].style.display = 'block';
    }

    function sendAction(action, likedUserId) {
        console.log('liked_user_id:', likedUserId);

        if (likedUserId !== 'undefined') {
            // Оставляем fetch без current_user_id
            fetch(`/main/like/`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                },
                body: `liked_user_id=${likedUserId}`, // Передаем только liked_user_id
            })
            .then(response => response.json())
            .then(data => {
                console.log(data);
                showCard(1);
            })
            .catch(error => console.error('Error:', error));
        }
    }

    // Обработчик события загрузки страницы
    window.onload = function () {
        // Показываем первую карточку при загрузке страницы
        showCard(0);
    };
</script>


</body>


{% endblock %}