blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, \
    BlogManagementListView

app_name = 'blog'

urlpatterns = [
    path('create/', BlogCreateView.as_view(template_name='blog/blog_form.html'), name='create'),
    path('', cache_page(60)(BlogListView.as_view(template_name='blog/blog_list.html')), name='list'),
    path('blog_management/', BlogManagementListView.as_view(template_name='blog/blog_management.html'), name='content'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view(template_name='blog/blog_detail.html')), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(template_name='blog/blog_form.html'), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(template_name='blog/blog_confirm_delete.html'), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    # path('chat/', include('chat.urls', namespace='chat')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
]


handler403 = 'mailing.views.custom_permission_denied'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from mailing.views import PartnerCreateView, ClientsListCreateView, mailing_panel, MailingCreateView, mailings_manage, \
    PartnerListView, MailingListView, MailingDetailView, toggle_block_status, MailingPartnersListView, \
    MailingPartnersDetailView, MailingPartnersUpdateView, MailingPartnersDeleteView, PartnersDetailView, \
    toggle_block_partners

app_name = 'mailing'

urlpatterns = [
    path('partner_registration/', PartnerCreateView.as_view(template_name='mailing/partner_registration.html'),
         name='partner_registration'),
    path('client_list_create/', ClientsListCreateView.as_view(), name='client_list_create'),
    path('mailing_management/', mailing_panel, name='mailing_panel'),
    path('mailing_form/', MailingCreateView.as_view(), name='mailing_form'),
    path('manage_mailing/', mailings_manage, name='mailings_manage'),
    path('partners_list_manage/', PartnerListView.as_view(), name='partners_list_manage'),
    path('mailings_list_manage/', MailingListView.as_view(), name='mailings_list_manage'),
    path('mailing_detail_manage/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail_manage'),
    path('toggle_block_status/<int:mailing_id>/', toggle_block_status, name='toggle_block_status'),
    path('mailings_list_user/', MailingPartnersListView.as_view(), name='mailings_list_user'),
    path('mailing_detail_user/<int:pk>/', MailingPartnersDetailView.as_view(), name='mailing_detail_user'),
    path('mailing_update_user/<int:pk>/', MailingPartnersUpdateView.as_view(), name='mailing_update_user'),
    path('mailing_confirm_delete/<int:pk>/', MailingPartnersDeleteView.as_view(), name='mailing_confirm_delete'),
    path('partners_detail_manage/<int:pk>/', PartnersDetailView.as_view(), name='partners_detail_manage'),
    path('toggle_block_partners/<int:partner_id>/', toggle_block_partners, name='toggle_block_partners'),

]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import UserProfileListView, UserProfileDetailView, administrative_panel, like_view, BlogListView


app_name = MainConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='main'),
    path('skylove_list_view/', UserProfileListView.as_view(), name='skylove_list_view'),
    path('main/like/', like_view, name='like_view'),
    path('administrative_panel/', administrative_panel, name='administrative_panel'),
    path('profile_view/<int:pk>', UserProfileDetailView.as_view(), name='profile_view'),

]

users/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, activate, email_activate, restore_password, VerifyEmailView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('activate/<str:uid>/', activate, name="activate"),
    path('email_activated/', email_activate, name="email_activated"),
    path('restore_password/', restore_password, name="restore_password"),
    path('verify_email/<int:pk>/', VerifyEmailView.as_view(), name='verify_email'),
]

main/models.py
from django.db import models

from users.models import User


class Likes(models.Model):
    """
    Модель для записи лайка (кто лайкнул, кого лайкнул)
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes_given')
    liked_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes_received')
    created_at = models.DateTimeField(auto_now_add=True)

main/views.py
from django.views.decorators.cache import cache_page

from blog.forms import BlogForm
from blog.models import Blog
from mailing.models import Mailing, Client
from users.models import User

from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import permission_required


from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from main.utils import record_like


class UserProfileListView(LoginRequiredMixin, ListView):
    """
    Класс для создания списка анкет
    """
    model = User
    template_name = 'main/skylove_list_view.html'
    # permission_required = 'user.view_user'


class UserProfileDetailView(LoginRequiredMixin, DetailView):
    """
    Класс для отображения анкеты
    """

    model = User
    template_name = 'main/profile_view.html'
    # permission_required = 'user.view_user'

#применяем кэширование контроллера
@cache_page(60)
@csrf_exempt
@require_POST
def like_view(request):
    try:
        # Получаем id текущего пользователя
        user_id = request.user.id

        # Получаем id пользователя, которого лайкнули
        liked_user_id = request.POST.get('liked_user_id')
        print('current_user_id:', user_id)
        print('liked_user_id:', liked_user_id)

        # Вызываем функцию для записи лайка
        record_like(user_id, int(liked_user_id))

        return JsonResponse({'status': 'success'})
    except Exception as e:
        print('Error:', e)
        return JsonResponse({'status': 'error', 'message': str(e)})


@permission_required('mailing.can_blocked')
def administrative_panel(request):
    return render(request, 'main/administrative_panel.html')


class BlogListView(ListView):
    """
    Класс для создания списка блоговых записей
    """
    model = Blog
    form_class = BlogForm
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Получите общее количество рассылок
        total_mailings = Mailing.objects.count()

        active_mailings = Mailing.objects.filter(is_active=True).count()

        total_clients = Client.objects.count()

        # Передайте информацию в контекст
        context['total_mailings'] = total_mailings
        context['active_mailings'] = active_mailings
        context['total_clients'] = total_clients

        return context

main/templates/main/includes/inc_main_menu.html
<div class="col-sm-8 offset-md-0 py-4">
  <h4 class="text-white">Меню</h4>
  <ul class="list-unstyled">
    <li><a href="{% url 'main:main' %}" class="text-white">Главная</a></li>
    <li><a href="{% url 'main:skylove_list_view' %}" class="text-white">SkyLove</a></li>
    <li><a href="/blog/" class="text-white">Блог</a></li>
  </ul>
</div>

<div class="col-sm-4 offset-md-0 py-4">
    <h4 class="text-white">Личный кабинет</h4>
    <ul class="list-unstyled">
        {% if user.is_authenticated %}
            {% if user.avatar  %}
                <li>
                    <form action="{% url 'users:profile' %}">
                    {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-outline-secondary text-white btn-logout">Профиль:</button><font color="green" size='3'> {{ user }} </font><img src="{{ user.avatar.url }}" alt="Avatar" width="30" height="30">
                    </form>
                </li>
            {% else %}
                <li>
                    <form action="{% url 'users:profile' %}">
                    {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-outline-secondary text-white btn-logout">Профиль: <font color="green" size='3'> {{ user }} </font></button>
                    </form>
                </li>
            {% endif %}
            <li>
                <form action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-outline-secondary text-white btn-logout">Выйти</button>
                </form>
                {% if not user.partner %}
                <form action="{% url 'mailing:partner_registration' %}">
                    {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-outline-secondary text-white btn-logout">Стать партнером</button>
                </form>
                {% endif %}
                <form action="/admin/">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-outline-secondary text-white btn-logout">Админ</button>
                </form>
                <form action="{% url 'mailing:mailing_panel' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-outline-secondary text-white btn-logout">Рассылки</button>
                </form>
                {% if perms.mailing.can_blocked %}
                <form action="{% url 'main:administrative_panel' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-outline-secondary text-white btn-logout">Управление</button>
                </form>
                {% endif %}
            </li>
        {% else %}
            <li>
                <form action="{% url 'users:register' %}">
                {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-outline-secondary text-white btn-logout">Регистрация</button>
                </form>
            </li>
            <li>
                <form action="{% url 'users:login' %}">
                {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-outline-secondary text-white btn-logout">Войти</button>
                </form>
            </li>
        {% endif %}
    </ul>
</div>